### ISSUE TITLE
Кодировки для русского языка + собрать dll

### ISSUE THREAD

**Issue by nik0rai** [RRPteam1/Lab2#4]

**Comment by nik0rai** [comment]
Чтобы закрыть пишите `commit -m "fix #ваш_номер"`

**Comment by kucherovaK** [comment]
Задача "Собрать dll"
**Создание и подключение библиотеки классов**:
_Возьмем имеющийся проект консольного приложения C#._ 

- В структуре проекта нажать правой кнопкой на название решения и далее в меню выбрать Add -> New Project...
- Далее из списке шаблонов выбрать проект Class Library. Для его создания необходимо назвать проект -> Next.

### После создания этого проекта в решение будет добавлен новый проект

По умолчанию новый проект имеет один пустой класс Class1 в файле Class1.cs. Можно этот файл удалить или переименовать.

- После того как переименовали можем добавить код класса.

### Например:
`namespace MyLib
{
    public class Person
    {
        string name;
        public Person(string name) 
        {
            this.name = name;
        }
        public void Print() => Console.WriteLine($"Name: {name}");
    }
}`

- Скомпилируем библиотеку классов. Для этого нужно нажать правой кнопкой на проект библиотеки классов и в контекстном меню выберем пункт Rebuild
- Подключим dll в основной проект. Для этого в основном проекте нажмем правой кнопкой на узел Dependencies и в контекстном меню выберем пункт Add Project Reference...
- Затем откроется окно для добавления библиотек. В этом окне выберем пункт Solution, поставим отметку рядом с нужной библиотекой и нажмем на кнопку OK

_Если наша библиотека вдруг представляет файл dll, который не связан ни с каким проектом в нашем решении, то с помощью кнопки Browse мы можем найти местоположение файла dll и также его подключить._

Подробнее с картинками можно посмотреть здесь: [https://metanit.com/sharp/tutorial/3.46.php](url)

**Comment by kucherovaK** [comment]
Грамотное использование русских символов в заголовках почтового сообщения

В явном виде русский текст в заголовке присутствовать не должен, поэтому для того, чтобы включить его туда, этот текст предварительно нужно закодировать. Стандарты описывают способ кодирования «запрещенных» символов. Общий формат выглядит так:

`=? кодировка? способ кодирования? закодированный текст?=
`
Кодировка может быть любой из списка «windows-1251», «koi8-r», «utf-8» и т.д. Во всех случаях, как правило, кодировка сообщения будет совпадать с кодировкой в которой работает сайт. В современных приложениях отдается предпочтение [Юникоду](https://ru.wikipedia.org/wiki/%D0%AE%D0%BD%D0%B8%D0%BA%D0%BE%D0%B4) ([UTF-8](https://ru.wikipedia.org/wiki/UTF-8))

Способ кодирования указывает на то, каким именно образом русские символы будут преобразованы в безопасный набор. Способа определяется два: «Q-encoding»и «Base64».

К сожалению, штатной функции, которая бы могла бы обычную строку преобразовать в Q-encoded текст, в PHP нет, зато есть функция, которая умеет выполнять аналогичное преобразование в Base64. Итак, PHP код правильного создания заголовка темы почтового сообщения может выглядеть следующим образом:

`$subject = "=?windows-1251?b?". base64_encode($_POST[«subject»]). "?=";
`
_Здесь предполагается, что в переменной $_POST[«subject»] у вас содержится тема почтового сообщения, записанная по-русски в кодировке windows-1251._

Адрес отправителя или получателя может быть записан в виде «user@example.com» или в виде «Имя пользователя <user@example.com>». Во втором случае имя пользователя необходимо преобразовать так же, как в предыдущем примере. Ниже приведен пример, в котором предполагается, что в переменной $_POST[«username»] содержится имя пользователя, а в переменной $_POST[«email»] его электронный адрес:

`$sender = "=?windows-1251?B?". base64_encode($_POST[«username»]). "?= <". $_POST[«email»]. ">";`


Документация «utf-8»: [https://learn.microsoft.com/ru-ru/dotnet/api/system.text.utf8encoding?view=net-7.0](url)

**Comment by kucherovaK** [comment]
Создание и подключение библиотеки классов dll.

- Возьмем имеющийся проект консольного приложения C#

-  В структуре проекта нажать правой кнопкой на название решения и далее в появившемся контекстном меню выбрать Add -> New Project...

- Далее в списке шаблонов проекта найдем пункт Class Library

- Затем новый проект назвать и нажать Next.

_После создания этого проекта в решение будет добавлен новый проект_
_По умолчанию новый проект имеет один пустой класс Class1 в файле Class1.cs.  Этот файл можно удалить или переименовать.

_Например_, переименуем файл Class1.cs в Person.cs, а класс Class1 в Person. Определим в классе Person простейший код:

```
namespace MyLib
{
    public class Person
    {
        string name;
        public Person(string name) 
        {
            this.name = name;
        }
        public void Print() => Console.WriteLine($"Name: {name}");
    }
}
```

- Скомпилируем библиотеку классов. Для этого правой кнопкой нажать на проект библиотеки классов и в контекстном меню выбрать пункт Rebuild

- Подключение dll в основной проект. Для этого в основном проекте нажмем правой кнопкой на узел Dependencies и в контекстном меню выберем пункт Add Project Reference...

- Далее откроется окно для добавления библиотек. В этом окне выбрать пункт Solution -> поставим отметку рядом с нашей библиотекой и нажать на кнопку OK

_Если наша библиотека вдруг представляет файл dll, который не связан ни с каким проектом в нашем решении, то с помощью кнопки Browse мы можем найти местоположение файла dll и также его подключить._


Подробнее с картинками можно посмотреть: [https://metanit.com/sharp/tutorial/3.46.php](url)

**Comment by nik0rai** [comment]
Кодировку сделал
